import type { LucideIcon } from 'lucide-react';
import {
  LayoutDashboard,
  Users,
  Shield,
  Warehouse,
  Settings,
  Building2,
  GitBranch,
  MapPin,
  Layers,
  ClipboardList,
  BarChart3,
  ScrollText,
  Smartphone,
  QrCode,
  Package,
  FileText,
  ArrowRightLeft,
  Boxes,
  Truck,
  RotateCcw,
  Sliders,
  History,
  Activity,
  UserCheck,
  Split,
  Sparkles,
} from 'lucide-react';

/** Icon map keyed by route href — keeps navigation config permission-only */
export const NAV_ICONS: Record<string, LucideIcon> = {
  '/dashboard': LayoutDashboard,
  '/companies': Building2,
  '/branches': GitBranch,
  '/sites': MapPin,
  '/warehouses': Warehouse,
  '/rooms': Layers,
  '/rows': Layers,
  '/racks': Layers,
  '/rack-templates': Sparkles,
  '/levels': Layers,
  '/locations': MapPin,
  '/box-types': Package,
  '/file-types': FileText,
  '/boxes': Package,
  '/file-records': FileText,
  '/barcodes/master': QrCode,
  '/barcodes': QrCode,
  '/status-master': Activity,
  '/departments': Building2,
  '/clients': Users,
  '/users': UserCheck,
  '/roles': Shield,
  '/work-orders': Sliders,
  '/inventory-movements': ArrowRightLeft,
  '/workflows/fresh-box-move': Boxes,
  '/workflows/segregation': Truck,
  '/workflows/refile': RotateCcw,
  '/workflows/merge': Split,
  '/workflows/inventory-verification': ClipboardList,
  '/workflows/transfer': Sliders,
  '/reports': BarChart3,
  '/audit-logs': ScrollText,
  '/devices': Smartphone,
  '/sync': History,
  '/settings': Settings,
};

export function getNavIcon(href: string): LucideIcon {
  return NAV_ICONS[href] ?? Layers;
}
