import { ColumnDef } from '@tanstack/react-table';
import { Package, FileText, Users, Calendar, Download, RefreshCw, AlertCircle } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { ReportJob } from '@/lib/types/report';

export const columns: ColumnDef<ReportJob>[] = [
  {
    accessorKey: 'name',
    header: () => <span className="text-xs font-bold tracking-wider text-slate-500 uppercase">Report Name</span>,
    cell: ({ row, table }) => {
      const report = row.original;
      const meta = table.options.meta as any;
      return (
        <div 
          className="flex items-center gap-3 py-1 cursor-pointer group"
          onClick={() => meta?.onCustomAction?.(report)}
        >
          <div className="flex items-center justify-center w-9 h-9 rounded-xl bg-blue-50 text-blue-600 border border-blue-100 group-hover:scale-105 transition-transform duration-200">
            <FileText className="w-4.5 h-4.5" />
          </div>
          <div className="flex flex-col">
            <span className="font-semibold text-slate-900 text-sm leading-snug group-hover:text-blue-600 transition-colors duration-200">
              {report.name}
            </span>
            <span className="text-[10px] text-slate-400 mt-0.5 font-mono select-all">
              ID: {report.id}
            </span>
          </div>
        </div>
      );
    },
  },
  {
    accessorKey: 'type',
    header: () => <span className="text-xs font-bold tracking-wider text-slate-500 uppercase">Type</span>,
    cell: ({ row }) => {
      const type = row.getValue('type') as string;
      const styles = {
        INVENTORY: 'bg-blue-50 text-blue-700 border-blue-100',
        ACTIVITY: 'bg-emerald-50 text-emerald-700 border-emerald-100',
        AUDIT: 'bg-purple-50 text-purple-700 border-purple-100',
        PERFORMANCE: 'bg-amber-50 text-amber-700 border-amber-100',
      };
      const icons = {
        INVENTORY: <Package className="w-3.5 h-3.5 text-blue-500" />,
        ACTIVITY: <FileText className="w-3.5 h-3.5 text-emerald-500" />,
        AUDIT: <Users className="w-3.5 h-3.5 text-purple-500" />,
        PERFORMANCE: <Calendar className="w-3.5 h-3.5 text-amber-500" />,
      };
      return (
        <span className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-xl text-xs font-bold border ${
          styles[type as keyof typeof styles] || styles.INVENTORY
        }`}>
          {icons[type as keyof typeof icons]}
          {type}
        </span>
      );
    },
  },
  {
    accessorKey: 'description',
    header: () => <span className="text-xs font-bold tracking-wider text-slate-500 uppercase">Description</span>,
    cell: ({ row }) => (
      <div className="text-xs text-slate-500 font-semibold max-w-[200px] truncate">
        {row.getValue('description')}
      </div>
    ),
  },
  {
    accessorKey: 'generatedBy',
    header: () => <span className="text-xs font-bold tracking-wider text-slate-500 uppercase">Generated By</span>,
    cell: ({ row }) => (
      <div className="text-xs font-bold text-slate-700">
        {row.getValue('generatedBy')}
      </div>
    ),
  },
  {
    accessorKey: 'createdAt',
    header: () => <span className="text-xs font-bold tracking-wider text-slate-500 uppercase">Generated At</span>,
    cell: ({ row }) => {
      const date = new Date(row.getValue('createdAt'));
      return (
        <div className="flex items-center gap-1.5 text-xs text-slate-500 font-medium">
          <Calendar className="w-3.5 h-3.5 text-slate-400" />
          {date.toLocaleDateString(undefined, { year: 'numeric', month: 'short', day: 'numeric' })}
        </div>
      );
    },
  },
  {
    accessorKey: 'status',
    header: () => <span className="text-xs font-bold tracking-wider text-slate-500 uppercase">Status</span>,
    cell: ({ row }) => {
      const status = row.getValue('status') as string;
      const styles = {
        READY: 'bg-emerald-50 text-emerald-700 border-emerald-200',
        GENERATING: 'bg-amber-50 text-amber-700 border-amber-200',
        FAILED: 'bg-rose-50 text-rose-700 border-rose-200',
      };
      return (
        <span className={`inline-flex items-center gap-1.5 px-3 py-1 rounded-xl text-xs font-bold border ${
          styles[status as keyof typeof styles] || styles.READY
        }`}>
          {status === 'GENERATING' && <RefreshCw className="w-3 h-3 animate-spin text-amber-500" />}
          {status === 'FAILED' && <AlertCircle className="w-3.5 h-3.5 text-rose-500" />}
          {status}
        </span>
      );
    },
  },
  {
    id: 'actions',
    header: () => <span className="text-xs font-bold tracking-wider text-slate-500 uppercase">Actions</span>,
    cell: ({ row }) => {
      const report = row.original;
      return (
        <div>
          {report.status === 'READY' && report.fileUrl ? (
            <Button 
              variant="outline" 
              className="h-8 rounded-xl px-3 text-xs font-bold border-slate-200 hover:bg-slate-50 text-slate-700 transition-colors"
              onClick={() => alert(`Downloading: ${report.name}`)}
            >
              <Download className="w-3.5 h-3.5 mr-1 text-slate-550" />
              Download
            </Button>
          ) : report.status === 'GENERATING' ? (
            <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wide">Processing...</span>
          ) : (
            <span className="text-[10px] font-bold text-rose-500 uppercase tracking-wide">Error</span>
          )}
        </div>
      );
    },
  },
];
